// Large cold rooms (cs_id >= 10) — same list the old universal check-in page used.
export const ROOM_CONFIG = [
  { cs_id: 10, cs_name: "CSR5-6" },
  { cs_id: 11, cs_name: "CHILL 11" },
  { cs_id: 12, cs_name: "CSR 8" },
  { cs_id: 13, cs_name: "CSR 9" },
  { cs_id: 14, cs_name: "CSR 10" },
  { cs_id: 15, cs_name: "CSR 11" },
  { cs_id: 16, cs_name: "Freeze 5" },
  { cs_id: 17, cs_name: "Freeze 6" },
  { cs_id: 18, cs_name: "CHILL 8" },
  { cs_id: 19, cs_name: "CHILL 9" },
  { cs_id: 20, cs_name: "CHILL 10" },
  { cs_id: 21, cs_name: "CSR 14" },
  { cs_id: 22, cs_name: "AIR LOCK 2A2B" },
  { cs_id: 23, cs_name: "Ante 2B" },
  { cs_id: 24, cs_name: "Ante 2C" },
  { cs_id: 25, cs_name: "CSR 12A" },
  { cs_id: 26, cs_name: "CSR 12B" },
  { cs_id: 27, cs_name: "Freeze 11" },
  { cs_id: 28, cs_name: "Freeze 12" },
  { cs_id: 29, cs_name: "Ante 3A" },
  { cs_id: 30, cs_name: "Ante 3B" },
  { cs_id: 31, cs_name: "TUNA Line" },
  { cs_id: 32, cs_name: "ANTE 2A" },
  { cs_id: 33, cs_name: "CSR 4B" },
  { cs_id: 34, cs_name: "AIR LOCK 3A" },
  { cs_id: 35, cs_name: "Solar rooftop" },
  { cs_id: 36, cs_name: "ห้องเก็บเคมี WH" },
  { cs_id: 37, cs_name: "MDB room RF1" },
  { cs_id: 38, cs_name: "ห้องเก็บผัก" },
  { cs_id: 39, cs_name: "วัตถุดิบฟรีส11/1" },
  { cs_id: 40, cs_name: "วัตถุดิบฟรีส 11/2" },
  { cs_id: 41, cs_name: "วัตถุดิบฟรีส 11/3" },
  { cs_id: 42, cs_name: "วัตถุดิบฟรีส 11/4" },
  { cs_id: 43, cs_name: "วัตถุดิบฟรีส 12/1" },
  { cs_id: 44, cs_name: "วัตถุดิบฟรีส 12/2" },
  { cs_id: 45, cs_name: "วัตถุดิบฟรีส 12/3" },
  { cs_id: 46, cs_name: "วัตถุดิบฟรีส 12/4" },
];
